### PR TITLE
NLP bugs and Policies

### PR DESCRIPTION
**Pull request by thedecider**
Added more support for the NLP output and made an initial "policyCutter"
which makes updating the table a bit easier (needs more work)

### CODE REVIEW

**Comment by Meneth** [comment]
Is there a reason it is a whole separate file, with a lot of code duplicated from the main parser file? In general that's something that should be avoided if at all possible, since it can easily lead to code being out of sync.

**Comment by thedecider** [comment]
The policyCutter needs to suck the information of 3 files and generate a table of all combinations, I solved this by preprocessing the 3 policy files using the regular parser with just a slight modification ona  few lines(I guess an If-check could be added to see if its run in a "policyMode" or something) in order to take advantage of the parser's output ability(and getting the effects of the policy right!). After this I run through the "barebones" files and build my table which is later output into a final file. The storage of the "barebones"-files I suppose could be handled in memory, reducing the overall number of output files of the policy file.

**Comment by Meneth** [comment]
If necessary, just add another field to the settings file. Code duplication is one of the biggest programming sins.

**Comment by thedecider** [comment]
Yeah, I didn't wan't to risk messing up the regular parser ("Do not disturb my circles!"), but now that the development has settled in on a design I could do that.

**Comment by Meneth** [comment]
The parser is such a mess, it is hard to mess it up any further.
It was my first sizable programming project; I'd only been coding Python (my first language) for something like two weeks when I started on it. So I didn't exactly know all the best practices.
Thus, it is pretty damn messy. I've cleaned it up a bit over time by pulling things out into functions, but what it really needs is a full rewrite. I'm considering just rewriting it in Java at some point in order to make it properly structured and extensible.

**Comment by thedecider** [comment]
The policyCutter is now inside the parser, added a setting to enable it.
I don't know which language number Python is for me, but I managed to pick it up and fulfill my goal within 6 hours :) What I like about it having done this little project is that it's very lightweight, all you need is Notepad++, Google is your friend.

**Comment by Meneth** [comment]
Python is a lovely language. It doesn't force structure like Java and other languages that force object orientation do though.

**Comment by Meneth** [comment]
Right. Merged. It might make sense to translate the policy variable into a boolean though. Checking policy == "yes" hurts my programming sensibilities.

**Comment by thedecider** [comment]
...alright, patched

**Pull request merged**
